config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :employees

  #public pages routes
  get 'about' => 'pages#about_us'
  get 'contact' => 'pages#contact_us'
  get 'privacy-policy' => 'pages#privacy_policy'
  get 'terms-and-conditions' => 'pages#terms_and_conditions'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
	validates :first_name, :last_name , presence: true
	validates :personal_email , presence: true , uniqueness: true
	validates :city, :state, :country, :pincode, :address_line_1, presence: true

	def name
		"#{first_name} #{last_name}".strip
	end

	def full_address
		"#{address_line_1} #{city} #{state} #{country} #{pincode}".strip
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	def index
		@employees = Employee.all
	end

	def new
		@employee = Employee.new
	end

	def create
		@employee = Employee.new(employee_params)
		if @employee.save
			redirect_to employees_path , notice: 'Employee has been created Successfully!'
		else
			render :new
		end
	end

	def edit
		@employee = Employee.find(params[:id])
	end

	def update
		@employee = Employee.find(params[:id])
		if @employee.update(employee_params)
			redirect_to employees_path , notice: 'Employee has been updated Successfully!'
		else
			render :new
		end
	end

	def employee_params
		params.require(:employee).permit(:first_name , :middle_name , :last_name , :personal_email,
			:city , :state , :country , :pincode , :address_line_1 , :address_line_2)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@title = "Hello Niladri!";
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about_us
  end

  def contact_us
  end

  def privacy_policy
  end

  def terms_and_conditions
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/employees/edit.html.erb
<div class="col-lg-12">
    <div class="card mt-5 mb-5 rounded-0">
	    <div class="card-body">
		    <h2 class="text-center">Edit Employee information</h2>
	    </div>
    </div>
    
    <%= form_with model: @employee do |form| %>
    <div class="row">
    	<div class="col-lg-4">
    		<div class="form-group">
    			<%= form.label :first_name , class: 'mb-2' %>
    			<%= form.text_field :first_name , class: 'form-control form-control-lg rounded-0' %>
                <% @employee.errors.full_messages_for(:first_name).each do |message| %>
                <p class="text-danger"><%= message %></p>
                <% end %>
    		</div>
    	</div>
    	<div class="col-lg-4">
    		<div class="form-group">
    			<%= form.label :middle_name , class: 'mb-2' %>
    			<%= form.text_field :middle_name , class: 'form-control form-control-lg rounded-0' %>
    		</div>
    	</div>
    	<div class="col-lg-4">
    		<div class="form-group">
    			<%= form.label :last_name , class: 'mb-2' %>
    			<%= form.text_field :last_name , class: 'form-control form-control-lg rounded-0' %>
                <% @employee.errors.full_messages_for(:last_name).each do |message| %>
                <p class="text-danger"><%= message %></p>
                <% end %>
    		</div>
    	</div>
    	<div class="col-lg-4">
    		<div class="form-group">
    			<%= form.label :personal_email , class: 'mb-2' %>
    			<%= form.email_field :personal_email , class: 'form-control form-control-lg rounded-0' %>
                <% @employee.errors.full_messages_for(:personal_email).each do |message| %>
                <p class="text-danger"><%= message %></p>
                <% end %>
    		</div>
    	</div>
    	<div class="row">
    	<div class="col-lg-6">
    		<div class="form-group">
    			<%= form.label :address_line_1 , class: 'mb-2' %>
    			<%= form.text_field :address_line_1 , class: 'form-control form-control-lg rounded-0' %>
                <% @employee.errors.full_messages_for(:address_line_1).each do |message| %>
                <p class="text-danger"><%= message %></p>
                <% end %>
    		</div>
    	</div>
    	<div class="col-lg-6">
    		<div class="form-group">
    			<%= form.label :address_line_2 , class: 'mb-2' %>
    			<%= form.text_field :address_line_2 , class: 'form-control form-control-lg rounded-0' %>
    		</div>
    	</div>
    	</div>
    	<div class="row">
    	<div class="col-lg-3">
    		<div class="form-group">
    			<%= form.label :city , class: 'mb-2' %>
    			<%= form.text_field :city , class: 'form-control form-control-lg rounded-0' %>
                <% @employee.errors.full_messages_for(:city).each do |message| %>
                <p class="text-danger"><%= message %></p>
                <% end %>
    		</div>
    	</div>
    	<div class="col-lg-3">
    		<div class="form-group">
    			<%= form.label :state , class: 'mb-2' %>
    			<%= form.text_field :state , class: 'form-control form-control-lg rounded-0' %>
                <% @employee.errors.full_messages_for(:state).each do |message| %>
                <p class="text-danger"><%= message %></p>
                <% end %>
    		</div>
    	</div>
    	<div class="col-lg-3">
    		<div class="form-group">
    			<%= form.label :country , class: 'mb-2' %>
    			<%= form.text_field :country , class: 'form-control form-control-lg rounded-0' %>
                <% @employee.errors.full_messages_for(:country).each do |message| %>
                <p class="text-danger"><%= message %></p>
                <% end %>
    		</div>
    	</div>
    	<div class="col-lg-3">
    		<div class="form-group">
    			<%= form.label :pincode , class: 'mb-2' %>
    			<%= form.text_field :pincode , class: 'form-control form-control-lg rounded-0' %>
                <% @employee.errors.full_messages_for(:pincode).each do |message| %>
                <p class="text-danger"><%= message %></p>
                <% end %>
    		</div>
    	</div>
    	</div>
    	<div class="row">
    		<div class="col-lg-12">
    		<%= form.submit class: 'btn btn-primary rounded-0 mt-4' %>
    		<%= link_to "Back" , employees_path , class: 'btn btn-outline-primary rounded-0 mt-4' %>
    		</div>
    	</div>
    </div>
    <% end %>
</div>

app/views/employees/index.html.erb
<div class="col-lg-12">
	<%= flash[:notice] %>
<div class="card mt-5 mb-5 rounded-0">
	<div class="card-body">
		<h2 class="text-center">Listing Employees</h2>
	</div>
</div>
<%= link_to 'Create New Employee' , new_employee_path , class: 'btn btn-primary btn-lg mb-4 rounded-0' %>
<table class="table table-bordered">
	<thead>
		<tr>
			<th>Name</th>
			<th>Email</th>
			<th>Address</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @employees.each do |employee| %>
		<tr>
			<td><%= employee.name %></td>
			<td><%= employee.personal_email %></td>
			<td><%= employee.full_address %></td>
			<td><%= link_to 'Edit' , edit_employee_path(employee) , class: 'btn btn-primary' %> </td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>

app/views/employees/new.html.erb
<div class="col-lg-12">
    <div class="card mt-5 mb-5 rounded-0">
	    <div class="card-body">
		    <h2 class="text-center">Create New Employee</h2>
	    </div>
    </div>
    
    <%= form_with model: @employee do |form| %>
    <div class="row">
    	<div class="col-lg-4">
    		<div class="form-group">
    			<%= form.label :first_name , class: 'mb-2' %>
    			<%= form.text_field :first_name , class: 'form-control form-control-lg rounded-0' %>
                <% @employee.errors.full_messages_for(:first_name).each do |message| %>
                <p class="text-danger"><%= message %></p>
                <% end %>
    		</div>
    	</div>
    	<div class="col-lg-4">
    		<div class="form-group">
    			<%= form.label :middle_name , class: 'mb-2' %>
    			<%= form.text_field :middle_name , class: 'form-control form-control-lg rounded-0' %>
    		</div>
    	</div>
    	<div class="col-lg-4">
    		<div class="form-group">
    			<%= form.label :last_name , class: 'mb-2' %>
    			<%= form.text_field :last_name , class: 'form-control form-control-lg rounded-0' %>
                <% @employee.errors.full_messages_for(:last_name).each do |message| %>
                <p class="text-danger"><%= message %></p>
                <% end %>
    		</div>
    	</div>
    	<div class="col-lg-4">
    		<div class="form-group">
    			<%= form.label :personal_email , class: 'mb-2' %>
    			<%= form.email_field :personal_email , class: 'form-control form-control-lg rounded-0' %>
                <% @employee.errors.full_messages_for(:personal_email).each do |message| %>
                <p class="text-danger"><%= message %></p>
                <% end %>
    		</div>
    	</div>
    	<div class="row">
    	<div class="col-lg-6">
    		<div class="form-group">
    			<%= form.label :address_line_1 , class: 'mb-2' %>
    			<%= form.text_field :address_line_1 , class: 'form-control form-control-lg rounded-0' %>
                <% @employee.errors.full_messages_for(:address_line_1).each do |message| %>
                <p class="text-danger"><%= message %></p>
                <% end %>
    		</div>
    	</div>
    	<div class="col-lg-6">
    		<div class="form-group">
    			<%= form.label :address_line_2 , class: 'mb-2' %>
    			<%= form.text_field :address_line_2 , class: 'form-control form-control-lg rounded-0' %>
    		</div>
    	</div>
    	</div>
    	<div class="row">
    	<div class="col-lg-3">
    		<div class="form-group">
    			<%= form.label :city , class: 'mb-2' %>
    			<%= form.text_field :city , class: 'form-control form-control-lg rounded-0' %>
                <% @employee.errors.full_messages_for(:city).each do |message| %>
                <p class="text-danger"><%= message %></p>
                <% end %>
    		</div>
    	</div>
    	<div class="col-lg-3">
    		<div class="form-group">
    			<%= form.label :state , class: 'mb-2' %>
    			<%= form.text_field :state , class: 'form-control form-control-lg rounded-0' %>
                <% @employee.errors.full_messages_for(:state).each do |message| %>
                <p class="text-danger"><%= message %></p>
                <% end %>
    		</div>
    	</div>
    	<div class="col-lg-3">
    		<div class="form-group">
    			<%= form.label :country , class: 'mb-2' %>
    			<%= form.text_field :country , class: 'form-control form-control-lg rounded-0' %>
                <% @employee.errors.full_messages_for(:country).each do |message| %>
                <p class="text-danger"><%= message %></p>
                <% end %>
    		</div>
    	</div>
    	<div class="col-lg-3">
    		<div class="form-group">
    			<%= form.label :pincode , class: 'mb-2' %>
    			<%= form.text_field :pincode , class: 'form-control form-control-lg rounded-0' %>
                <% @employee.errors.full_messages_for(:pincode).each do |message| %>
                <p class="text-danger"><%= message %></p>
                <% end %>
    		</div>
    	</div>
    	</div>
    	<div class="row">
    		<div class="col-lg-12">
    		<%= form.submit class: 'btn btn-primary rounded-0 mt-4' %>
    		<%= link_to "Back" , employees_path , class: 'btn btn-outline-primary rounded-0 mt-4' %>
    		</div>
    	</div>
    </div>
    <% end %>
</div>

app/views/home/index.html.erb
<h1><%= @title %></h1>
<%= render 'shared/links'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hr</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
    <%= render 'shared/footer' %>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/about_us.html.erb
<div class="col-lg-10 mx-auto">
	<div class="text-center mt-5 mb-4"><h1>About HR</h1></div>
	<%= render 'shared/dummy_content'%>
</div>
<%= render 'shared/links'%>

app/views/pages/contact_us.html.erb
<div class="col-lg-10 mx-auto">
	<div class="text-center mt-5 mb-4"><h1>Contact us</h1></div>
	<%= render 'shared/dummy_content'%>
</div>
<%= render 'shared/links'%>

app/views/pages/privacy_policy.html.erb
<div class="col-lg-10 mx-auto">
	<div class="text-center mt-5 mb-4"><h1>Privacy Policy</h1></div>
	<%= render 'shared/dummy_content'%>
</div>
<%= render 'shared/links'%>

app/views/pages/terms_and_conditions.html.erb
<div class="col-lg-10 mx-auto">
	<div class="text-center mt-5 mb-4"><h1>Terms and Conditions</h1></div>
	<%= render 'shared/dummy_content'%>
</div>
<%= render 'shared/links'%>

app/views/shared/_dummy_content.html.erb
<p class="lead">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.</p>

	<p class="lead">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.</p>

	<p class="lead">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.</p>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <%= link_to 'HR' , root_path , class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/shared/_links.html.erb
<%= link_to 'About' , about_path , target: '_blank'%>
<%= link_to 'Contact Us' , contact_path , target: '_blank'%>
<%= link_to 'Privacy Policy' , privacy_policy_path , target: '_blank'%>
<%= link_to 'Terms and Conditions' , terms_and_conditions_path , target: '_blank'%>